### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by MrKampf** [Barzahlen/Barzahlen-PHP#16]
```
Using version ^2.1 for barzahlen/barzahlen-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package barzahlen/barzahlen-php No version set (parsed as 1.0.0) is satisfiable by barzahlen/barzahlen-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by martinseener** [comment]
Hi @MrKampf,
sadly i cannot reproduce your problem. I've setup a plain fresh Debian 9 with php7 and only installed the following packages there (php7.0-cli, curl, git, zip, unzip) whereas PHP version is `7.0.27-0+deb9u1` and installed the latest composer (like described [here](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-debian-8)) and composers version is `1.6.5 (2018-05-04)`.

The output looks like this:

```
~$ composer require barzahlen/barzahlen-php
Using version ^2.1 for barzahlen/barzahlen-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 instlal, 0 updates, 0 removals
   - Installing barzahlen/barzahlen-php (v2.1.0): Downloading (100%)
Writing lock files
Generating autoload files
```

Can it be, that you cloned the repo and then ran composer?

**Comment by martinseener** [comment]
I will close this Issue since i haven't heard back from your for some time now. If you still have this problem, just tell me again.
