### ISSUE TITLE
Packagist.org releases

### ISSUE THREAD

**Issue by fromYukki** [Barzahlen/Barzahlen-PHP#4]
Hello!

May I ask you? 
You have packagist repository https://packagist.org/packages/barzahlen/barzahlen-php but you don't have any versions there. Please, can you create all of your released versions in the packagist repository? Usually it is enough to push one button ;)

Thank you

**Comment by fromYukki** [comment]
Oh! I see new release and version in the packagist repository!  Many thanks guys!

**Comment by adiebler** [comment]
You're very welcome. Composer support was added after v1.1.7 and therefore the version wasn't recognized. New v1.1.8 was added after composer support, so packagist can work with it.
